#! /bin/bash

#
# Lists the contents of all jar files in a certain directory
#

if [ "${1}" = "" ]; then
    echo "error: missing argument: directory"
    exit 1
fi
dir=${1}

if [ ! -d "${dir}" ]; then
    echo "error: directory '${dir}' doesn't exist"
    exit 1
fi


echo "Listing jar files in '${dir}' ...";
jarfiles=$(find ${dir} -maxdepth 1 -name '*.jar')
for jarfile in ${jarfiles}
do
   echo "${jarfile}:"
   jar tvf "${jarfile}"
done

