#!/bin/bash

if [ $# -lt 2 ]; then
  echo "error: missing argument(s)"
  echo "usage: ${0} <groupId> <artifactId>"
  exit 1
fi

group_id=${1}
artifact_id=${2}

mvn archetype:generate -DgroupId=${group_id} -DartifactId=${artifact_id} -DarchetypeGroupId=com.thepracticaldeveloper -DarchetypeArtifactId=archetype-java-basic-tpd -DarchetypeVersion=1.0.0
