#!/bin/bash

#
# Converts an .svg image to a high-resolution .png image
# Relies on inkscape being installed.
#

scriptname=$(basename ${0})

background="#FFFFFF"
opacity="1.0"
height=
width=

function print_usage() {
    echo "${scriptname} [OPTIONS] <source.svg> [<dest.png>]"
    echo ""
    echo "Options:"
    echo "--background=COLOR  Background color to set. Default: ${background}."
    echo "--opacity=VALUE     Background opacity (0.0 - 1.0). Default: ${opacity}."
    echo "--height=px         The height (in pixels) of the generated bitmap."
    echo "                    For example, 1024. For correct scaling, only "
    echo "                    specify one of --height and --width. Default: "
    echo "                    use svg height."
    echo "--width=px          The width (in pixels) of the generated bitmap."
    echo "                    For example, 1024. For correct scaling, only "
    echo "                    specify one of --height and --width. Default: "
    echo "                    use svg width."
    echo "--help              Show help text"

}

function die() {
    echo $@
    echo ""
    print_usage
    exit 1
}

for arg in $@; do
    case ${arg} in
        --background=*)
            background=${arg#*=}
            ;;
        --opacity=*)
            opacity=${arg#*=}
            ;;
        --height=*)
            height=${arg#*=}
            ;;
        --width=*)
            width=${arg#*=}
            ;;
        --help)
            print_usage
            exit 0
            ;;
        --*)
            die "error: unrecognized option: ${arg}"
            ;;
        *)
            # assume only positional arguments left
            break
    esac
    shift
done

if [ "${1}" =  "" ]; then
    die "error: no <source.svg> file given"
fi
source_svg=${1}

dest_png="$(echo ${source_svg} | sed 's/.svg//').png"
if [ "${2}" != "" ]; then
    dest_png=$2
fi
[ "${source_svg}" = "${dest_png}" ] && die "error: source and destination are the same file"

options="--export-background=${background} --export-background-opacity=${opacity}"
if [ -n "${height}" ]; then
    options="${options} --export-height=${height}"
fi
if [ -n "${width}" ]; then
    options="${options} --export-width=${width}"
fi

inkscape --export-area-page --export-dpi=200 ${options} \
         --export-type=png --export-filename=${dest_png} ${source_svg}
