#!/bin/bash

#
# Converts an .svg image to a high-resolution .png image
# Relies on inkscape being installed.
#

scriptname=$(basename ${0})

background="#FFFFFF"
opacity="1.0"

function print_usage() {
    echo "${scriptname} [OPTIONS] <source.svg> [<dest.png>]"
    echo ""
    echo "Options:"
    echo "--background=COLOR  Background color to set. Default: ${background}."
    echo "--opacity=VALUE     Background opacity (0.0 - 1.0). Default: ${opacity}."
    echo "--help              Show help text"

}

function die() {
    echo $@
    echo ""
    print_usage
    exit 1
}

for arg in $@; do
    case ${arg} in
	--background=*)
	    background=${arg#*=}
	    ;;
	--opacity=*)
	    opacity=${arg#*=}
	    ;;
	--help)
	    print_usage
	    exit 0
	    ;;
	--*)
	    die "error: unrecognized option: ${arg}"
	    ;;
	*)
	    # assume only positional arguments left
	    break
    esac
    shift
done

if [ "${1}" =  "" ]; then
    die "error: no <source.svg> file given"
fi
source_svg=${1}

dest_png="$(echo ${source_svg} | sed 's/.svg//').png"
if [ "${2}" != "" ]; then
    dest_png=$2
fi    
[ "${source_svg}" = "${dest_png}" ] && die "error: source and destination are the same file"

inkscape --export-use-hints --export-area-drawing --export-background=${background} --export-background-opacity=${opacity} --export-dpi=200 --export-png=${dest_png} ${source_svg}
