#!/bin/bash

#
# Adds file/directory svn:ignore patterns to the current directory.
#

if [ "${#}" = "0" ]; then
   echo "error: missing argument: directory entry pattern(s) to ignore"
   echo "  usage: ${0} <ignore pattern> ..."
   exit 1
fi

existing_ignores=`svn propget svn:ignore`

# add entries to list
ignores="${existing_ignores}"
for ignore_pattern in ${@}; do
  ignores=`echo -e "${ignore_pattern}\n${ignores}"`   
done

echo -e "Setting the following svn:ignore(s) for the current directory:\n${ignores}"
# set svn:ignore
svn propset svn:ignore "${ignores}" .