#!/bin/bash

#
# Lists all TCP ports in TIME_WAIT state
#

netstat -ntp

if [ "$UID" -ne 0 ]; then
  echo
  echo "************************************************"
  echo "Note: for all open ports, run as privileged user"
  echo "************************************************"
fi
